version: '3.9'

services:
  frontend1:
    build:
      context: .
    container_name: frontend1
    ports:
      - "8081:80"
    networks:
      - app-network

  frontend2:
    build:
      context: .
    container_name: frontend2
    ports:
      - "8082:80"
    networks:
      - app-network

  frontend3:
    build:
      context: .
    container_name: frontend3
    ports:
      - "8083:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend1
      - frontend2
      - frontend3
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
