version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
   
  redis:
    image: redis:7
    networks:
      - app-network

  backend:
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    ports:
      - "8001:8000"
    networks:
      - app-network

  worker:
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    networks:
      - app-network

  beat:
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    command: celery -A app.celery_worker.celery_app beat --loglevel=info
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
